# coding: utf-8

"""
    Scrapix API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapix.models.output_format import OutputFormat

class TestOutputFormat(unittest.TestCase):
    """OutputFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutputFormat(self):
        """Test OutputFormat"""
        # inst = OutputFormat()

if __name__ == '__main__':
    unittest.main()
