/* tslint:disable */
/* eslint-disable */
/**
 * Scrapix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Input schema for collecting URLs from a page. `/collect`
 */
export interface CollectInput {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * Input URL
     */
    'url': string;
    /**
     * Timeout in seconds for the request
     */
    'timeout'?: number;
    /**
     * Max retries before failing
     */
    'max_retries'?: number;
    'max_cost'?: number | null;
    /**
     * Render the Page
     */
    'render'?: boolean;
    /**
     * Use premium proxy
     */
    'premium_proxies'?: boolean;
    /**
     * Use auto proxy: normal proxies (2 attempts) → premium proxies → render fallback
     */
    'auto_proxy'?: boolean;
    /**
     * Use captcha solvers to avoid blocking
     */
    'use_captcha_solver'?: boolean;
    /**
     * If enabled will serve from fresh crawl
     */
    'use_cache'?: boolean;
    /**
     * Maximum number of URLs to collect
     */
    'urls_limit'?: number;
    'exclude_paths'?: string | null;
    'include_paths'?: string | null;
    'query'?: string | null;
    /**
     * Include URLs from SiteMap
     */
    'include_sitemap_urls'?: boolean;
    /**
     * The format of the output
     */
    'output_format'?: StructuredOutputFormat;
}


/**
 * Result of collecting URLs from a page. `/collect`
 */
export interface CollectResult {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * The URL that was scraped
     */
    'url': string;
    /**
     * HTTP status code of the response
     */
    'status_code': number;
    /**
     * Whether the scraping was successful
     */
    'status': boolean;
    /**
     * HTTP headers of the response
     */
    'response_headers': { [key: string]: string; };
    /**
     * Credits used for the scraping task
     */
    'credits_used'?: number;
    /**
     * links extracted from the page
     */
    'links'?: StructuredOutput;
    'main_page'?: ScrapeResult | null;
}
/**
 * Input schema for crawling URLs from a page. `/crawl`
 */
export interface CrawlInput {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * Input URL
     */
    'url': string;
    /**
     * Timeout in seconds for the request
     */
    'timeout'?: number;
    /**
     * Max retries before failing
     */
    'max_retries'?: number;
    'max_cost'?: number | null;
    /**
     * Render the Page
     */
    'render'?: boolean;
    /**
     * Use premium proxy
     */
    'premium_proxies'?: boolean;
    /**
     * Use auto proxy: normal proxies (2 attempts) → premium proxies → render fallback
     */
    'auto_proxy'?: boolean;
    /**
     * Use captcha solvers to avoid blocking
     */
    'use_captcha_solver'?: boolean;
    /**
     * If enabled will serve from fresh crawl
     */
    'use_cache'?: boolean;
    /**
     * Maximum number of URLs to collect
     */
    'urls_limit'?: number;
    /**
     * The format of the output
     */
    'output_format'?: OutputFormat;
    /**
     * Include URLs from SiteMap
     */
    'include_sitemap_urls'?: boolean;
    'exclude_paths'?: string | null;
    'include_paths'?: string | null;
}


/**
 * Result of crawling URLs from a page. `/crawl`
 */
export interface CrawlResult {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * The URL that was scraped
     */
    'url': string;
    /**
     * HTTP status code of the response
     */
    'status_code': number;
    /**
     * Whether the scraping was successful
     */
    'status': boolean;
    /**
     * HTTP headers of the response
     */
    'response_headers': { [key: string]: string; };
    /**
     * Credits used for the scraping task
     */
    'credits_used'?: number;
    'main_page'?: ScrapeResult | null;
    /**
     * List of responses for each URL scraped
     */
    'responses': Array<ScrapeResult>;
}
export interface DataSerialized {
    'format': OutputFormat;
    'data': string;
}


/**
 * Input schema for extracting structured data or summarization from a page. `/extract`
 */
export interface ExtractInput {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * Input URL
     */
    'url': string;
    /**
     * Timeout in seconds for the request
     */
    'timeout'?: number;
    /**
     * Max retries before failing
     */
    'max_retries'?: number;
    'max_cost'?: number | null;
    /**
     * Render the Page
     */
    'render'?: boolean;
    /**
     * Use premium proxy
     */
    'premium_proxies'?: boolean;
    /**
     * Use auto proxy: normal proxies (2 attempts) → premium proxies → render fallback
     */
    'auto_proxy'?: boolean;
    /**
     * Use captcha solvers to avoid blocking
     */
    'use_captcha_solver'?: boolean;
    /**
     * If enabled will serve from fresh crawl
     */
    'use_cache'?: boolean;
    /**
     * The format of the output
     */
    'output_format'?: StructuredOutputFormat;
    'structured_schema'?: StructuredOutputSchema | null;
    'summarize_schema'?: SummarizeSchema | null;
    /**
     * Query for Structured output / Summarize / Instruct
     */
    'query': string;
}


/**
 * Result of extracting structured data or summarization from a page. `/extract`
 */
export interface ExtractResult {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * The URL that was scraped
     */
    'url': string;
    /**
     * HTTP status code of the response
     */
    'status_code': number;
    /**
     * Whether the scraping was successful
     */
    'status': boolean;
    /**
     * HTTP headers of the response
     */
    'response_headers': { [key: string]: string; };
    /**
     * Credits used for the scraping task
     */
    'credits_used'?: number;
    /**
     * Query for Structured output / Summarize / Instruct
     */
    'query': string;
    /**
     * Result of the query
     */
    'result': string;
    'final_html_page'?: string | null;
    /**
     * Cost incurred for the extraction
     */
    'cost'?: number;
    /**
     * Type of extraction agent used
     */
    'agent_type': string;
    'tokens_used'?: number | null;
    'structured_output'?: StructuredOutput | null;
}
export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface LocationInner {
}

export const OutputFormat = {
    Text: 'text',
    Html: 'html',
    Markdown: 'markdown',
    Docx: 'docx',
    Pdf: 'pdf',
    Base64: 'base64',
} as const;

export type OutputFormat = typeof OutputFormat[keyof typeof OutputFormat];


export interface ScrapeInput {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * Input URL
     */
    'url': string;
    /**
     * Timeout in seconds for the request
     */
    'timeout'?: number;
    /**
     * Max retries before failing
     */
    'max_retries'?: number;
    'max_cost'?: number | null;
    /**
     * Render the Page
     */
    'render'?: boolean;
    /**
     * Use premium proxy
     */
    'premium_proxies'?: boolean;
    /**
     * Use auto proxy: normal proxies (2 attempts) → premium proxies → render fallback
     */
    'auto_proxy'?: boolean;
    /**
     * Use captcha solvers to avoid blocking
     */
    'use_captcha_solver'?: boolean;
    /**
     * If enabled will serve from fresh crawl
     */
    'use_cache'?: boolean;
    /**
     * The format of the output
     */
    'output_format'?: OutputFormat;
    'structured_schema'?: StructuredOutputSchema | null;
    'summarize_schema'?: SummarizeSchema | null;
}


/**
 * Result of a single URL scrape. `/scrape`
 */
export interface ScrapeResult {
    /**
     * Unique identifier for the scraping task
     */
    'id'?: string;
    /**
     * The URL that was scraped
     */
    'url': string;
    /**
     * HTTP status code of the response
     */
    'status_code': number;
    /**
     * Whether the scraping was successful
     */
    'status': boolean;
    /**
     * HTTP headers of the response
     */
    'response_headers': { [key: string]: string; };
    /**
     * Credits used for the scraping task
     */
    'credits_used'?: number;
    /**
     * Content of the response
     */
    'data': DataSerialized;
    'structured_output'?: StructuredOutput | null;
    'summarized_data'?: { [key: string]: any; } | null;
}
/**
 * Structured output model for the response. This model is used to represent structured data extracted from the response.
 */
export interface StructuredOutput {
    /**
     * Structured data extracted from the response
     */
    'data': string;
    'data_schema'?: { [key: string]: any; } | null;
    /**
     * Format of the structured output
     */
    'format'?: StructuredOutputFormat;
    /**
     * Cost incurred for generating the structured output
     */
    'cost'?: number;
}



export const StructuredOutputFormat = {
    Json: 'json',
    Xml: 'xml',
    Yaml: 'yaml',
    Toml: 'toml',
} as const;

export type StructuredOutputFormat = typeof StructuredOutputFormat[keyof typeof StructuredOutputFormat];


export interface StructuredOutputSchema {
    /**
     * The format of the structured output schema
     */
    'format'?: StructuredOutputFormat;
    'schema'?: { [key: string]: any; } | null;
    /**
     * A user query on what to extract from the structured output
     */
    'query': string;
}


export interface SummarizeSchema {
    'query'?: string | null;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
    'input'?: any;
    'ctx'?: object;
}

/**
 * APIServicesApi - axios parameter creator
 */
export const APIServicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Collect Endpoint
         * @param {CollectInput} collectInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collect: async (collectInput: CollectInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'collectInput' is not null or undefined
            assertParamExists('collect', 'collectInput', collectInput)
            const localVarPath = `/v1/collect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(collectInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Crawl Endpoint
         * @param {CrawlInput} crawlInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        crawl: async (crawlInput: CrawlInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'crawlInput' is not null or undefined
            assertParamExists('crawl', 'crawlInput', crawlInput)
            const localVarPath = `/v1/crawl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(crawlInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Echo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/echo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Extract Endpoint
         * @param {ExtractInput} extractInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extract: async (extractInput: ExtractInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'extractInput' is not null or undefined
            assertParamExists('extract', 'extractInput', extractInput)
            const localVarPath = `/v1/extract`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(extractInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Scrape Endpoint
         * @param {ScrapeInput} scrapeInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scrape: async (scrapeInput: ScrapeInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'scrapeInput' is not null or undefined
            assertParamExists('scrape', 'scrapeInput', scrapeInput)
            const localVarPath = `/v1/scrape`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(scrapeInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * APIServicesApi - functional programming interface
 */
export const APIServicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = APIServicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Collect Endpoint
         * @param {CollectInput} collectInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collect(collectInput: CollectInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CollectResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.collect(collectInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.collect']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Crawl Endpoint
         * @param {CrawlInput} crawlInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async crawl(crawlInput: CrawlInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CrawlResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.crawl(crawlInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.crawl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Echo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async echo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.echo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.echo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Extract Endpoint
         * @param {ExtractInput} extractInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extract(extractInput: ExtractInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExtractResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extract(extractInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.extract']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Scrape Endpoint
         * @param {ScrapeInput} scrapeInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async scrape(scrapeInput: ScrapeInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ScrapeResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.scrape(scrapeInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.scrape']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * APIServicesApi - factory interface
 */
export const APIServicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = APIServicesApiFp(configuration)
    return {
        /**
         * 
         * @summary Collect Endpoint
         * @param {CollectInput} collectInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collect(collectInput: CollectInput, options?: RawAxiosRequestConfig): AxiosPromise<CollectResult> {
            return localVarFp.collect(collectInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Crawl Endpoint
         * @param {CrawlInput} crawlInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        crawl(crawlInput: CrawlInput, options?: RawAxiosRequestConfig): AxiosPromise<CrawlResult> {
            return localVarFp.crawl(crawlInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Echo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.echo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Extract Endpoint
         * @param {ExtractInput} extractInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extract(extractInput: ExtractInput, options?: RawAxiosRequestConfig): AxiosPromise<ExtractResult> {
            return localVarFp.extract(extractInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Scrape Endpoint
         * @param {ScrapeInput} scrapeInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scrape(scrapeInput: ScrapeInput, options?: RawAxiosRequestConfig): AxiosPromise<ScrapeResult> {
            return localVarFp.scrape(scrapeInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * APIServicesApi - interface
 */
export interface APIServicesApiInterface {
    /**
     * 
     * @summary Collect Endpoint
     * @param {CollectInput} collectInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    collect(collectInput: CollectInput, options?: RawAxiosRequestConfig): AxiosPromise<CollectResult>;

    /**
     * 
     * @summary Crawl Endpoint
     * @param {CrawlInput} crawlInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    crawl(crawlInput: CrawlInput, options?: RawAxiosRequestConfig): AxiosPromise<CrawlResult>;

    /**
     * 
     * @summary Echo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    echo(options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * 
     * @summary Extract Endpoint
     * @param {ExtractInput} extractInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    extract(extractInput: ExtractInput, options?: RawAxiosRequestConfig): AxiosPromise<ExtractResult>;

    /**
     * 
     * @summary Scrape Endpoint
     * @param {ScrapeInput} scrapeInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    scrape(scrapeInput: ScrapeInput, options?: RawAxiosRequestConfig): AxiosPromise<ScrapeResult>;

}

/**
 * APIServicesApi - object-oriented interface
 */
export class APIServicesApi extends BaseAPI implements APIServicesApiInterface {
    /**
     * 
     * @summary Collect Endpoint
     * @param {CollectInput} collectInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public collect(collectInput: CollectInput, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).collect(collectInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Crawl Endpoint
     * @param {CrawlInput} crawlInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public crawl(crawlInput: CrawlInput, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).crawl(crawlInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Echo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public echo(options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).echo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Extract Endpoint
     * @param {ExtractInput} extractInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public extract(extractInput: ExtractInput, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).extract(extractInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Scrape Endpoint
     * @param {ScrapeInput} scrapeInput 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public scrape(scrapeInput: ScrapeInput, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).scrape(scrapeInput, options).then((request) => request(this.axios, this.basePath));
    }
}



