/* tslint:disable */
/* eslint-disable */
/**
 * Scrapix API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";


// -- convenience helper (shipped via integrations/sdk/templates/scrapix/typescript/) --
export { createClient, DEFAULT_HOST } from "./helper";
