/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CollectInput } from '../models';
// @ts-ignore
import type { CollectResult } from '../models';
// @ts-ignore
import type { CrawlInput } from '../models';
// @ts-ignore
import type { CrawlResult } from '../models';
// @ts-ignore
import type { ExtractInput } from '../models';
// @ts-ignore
import type { ExtractResult } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { ScrapeInput } from '../models';
// @ts-ignore
import type { ScrapeResult } from '../models';
/**
 * APIServicesApi - axios parameter creator
 * @export
 */
export const APIServicesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Collect Endpoint
         * @param {CollectInput} collectInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collect: async (collectInput: CollectInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'collectInput' is not null or undefined
            assertParamExists('collect', 'collectInput', collectInput)
            const localVarPath = `/v1/collect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(collectInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Crawl Endpoint
         * @param {CrawlInput} crawlInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        crawl: async (crawlInput: CrawlInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'crawlInput' is not null or undefined
            assertParamExists('crawl', 'crawlInput', crawlInput)
            const localVarPath = `/v1/crawl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(crawlInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Echo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/echo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Extract Endpoint
         * @param {ExtractInput} extractInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extract: async (extractInput: ExtractInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'extractInput' is not null or undefined
            assertParamExists('extract', 'extractInput', extractInput)
            const localVarPath = `/v1/extract`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(extractInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Scrape Endpoint
         * @param {ScrapeInput} scrapeInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scrape: async (scrapeInput: ScrapeInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'scrapeInput' is not null or undefined
            assertParamExists('scrape', 'scrapeInput', scrapeInput)
            const localVarPath = `/v1/scrape`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication APIKeyHeader required
            await setApiKeyToObject(localVarHeaderParameter, "x-api-key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(scrapeInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * APIServicesApi - functional programming interface
 * @export
 */
export const APIServicesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = APIServicesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Collect Endpoint
         * @param {CollectInput} collectInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async collect(collectInput: CollectInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CollectResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.collect(collectInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.collect']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Crawl Endpoint
         * @param {CrawlInput} crawlInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async crawl(crawlInput: CrawlInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CrawlResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.crawl(crawlInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.crawl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Echo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async echo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.echo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.echo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Extract Endpoint
         * @param {ExtractInput} extractInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extract(extractInput: ExtractInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExtractResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extract(extractInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.extract']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Scrape Endpoint
         * @param {ScrapeInput} scrapeInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async scrape(scrapeInput: ScrapeInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ScrapeResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.scrape(scrapeInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['APIServicesApi.scrape']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * APIServicesApi - factory interface
 * @export
 */
export const APIServicesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = APIServicesApiFp(configuration)
    return {
        /**
         * 
         * @summary Collect Endpoint
         * @param {APIServicesApiCollectRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        collect(requestParameters: APIServicesApiCollectRequest, options?: RawAxiosRequestConfig): AxiosPromise<CollectResult> {
            return localVarFp.collect(requestParameters.collectInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Crawl Endpoint
         * @param {APIServicesApiCrawlRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        crawl(requestParameters: APIServicesApiCrawlRequest, options?: RawAxiosRequestConfig): AxiosPromise<CrawlResult> {
            return localVarFp.crawl(requestParameters.crawlInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Echo
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        echo(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.echo(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Extract Endpoint
         * @param {APIServicesApiExtractRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extract(requestParameters: APIServicesApiExtractRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExtractResult> {
            return localVarFp.extract(requestParameters.extractInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Scrape Endpoint
         * @param {APIServicesApiScrapeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scrape(requestParameters: APIServicesApiScrapeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ScrapeResult> {
            return localVarFp.scrape(requestParameters.scrapeInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * APIServicesApi - interface
 * @export
 * @interface APIServicesApi
 */
export interface APIServicesApiInterface {
    /**
     * 
     * @summary Collect Endpoint
     * @param {APIServicesApiCollectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApiInterface
     */
    collect(requestParameters: APIServicesApiCollectRequest, options?: RawAxiosRequestConfig): AxiosPromise<CollectResult>;

    /**
     * 
     * @summary Crawl Endpoint
     * @param {APIServicesApiCrawlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApiInterface
     */
    crawl(requestParameters: APIServicesApiCrawlRequest, options?: RawAxiosRequestConfig): AxiosPromise<CrawlResult>;

    /**
     * 
     * @summary Echo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApiInterface
     */
    echo(options?: RawAxiosRequestConfig): AxiosPromise<any>;

    /**
     * 
     * @summary Extract Endpoint
     * @param {APIServicesApiExtractRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApiInterface
     */
    extract(requestParameters: APIServicesApiExtractRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExtractResult>;

    /**
     * 
     * @summary Scrape Endpoint
     * @param {APIServicesApiScrapeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApiInterface
     */
    scrape(requestParameters: APIServicesApiScrapeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ScrapeResult>;

}

/**
 * Request parameters for collect operation in APIServicesApi.
 * @export
 * @interface APIServicesApiCollectRequest
 */
export interface APIServicesApiCollectRequest {
    /**
     * 
     * @type {CollectInput}
     * @memberof APIServicesApiCollect
     */
    readonly collectInput: CollectInput
}

/**
 * Request parameters for crawl operation in APIServicesApi.
 * @export
 * @interface APIServicesApiCrawlRequest
 */
export interface APIServicesApiCrawlRequest {
    /**
     * 
     * @type {CrawlInput}
     * @memberof APIServicesApiCrawl
     */
    readonly crawlInput: CrawlInput
}

/**
 * Request parameters for extract operation in APIServicesApi.
 * @export
 * @interface APIServicesApiExtractRequest
 */
export interface APIServicesApiExtractRequest {
    /**
     * 
     * @type {ExtractInput}
     * @memberof APIServicesApiExtract
     */
    readonly extractInput: ExtractInput
}

/**
 * Request parameters for scrape operation in APIServicesApi.
 * @export
 * @interface APIServicesApiScrapeRequest
 */
export interface APIServicesApiScrapeRequest {
    /**
     * 
     * @type {ScrapeInput}
     * @memberof APIServicesApiScrape
     */
    readonly scrapeInput: ScrapeInput
}

/**
 * APIServicesApi - object-oriented interface
 * @export
 * @class APIServicesApi
 * @extends {BaseAPI}
 */
export class APIServicesApi extends BaseAPI implements APIServicesApiInterface {
    /**
     * 
     * @summary Collect Endpoint
     * @param {APIServicesApiCollectRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApi
     */
    public collect(requestParameters: APIServicesApiCollectRequest, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).collect(requestParameters.collectInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Crawl Endpoint
     * @param {APIServicesApiCrawlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApi
     */
    public crawl(requestParameters: APIServicesApiCrawlRequest, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).crawl(requestParameters.crawlInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Echo
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApi
     */
    public echo(options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).echo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Extract Endpoint
     * @param {APIServicesApiExtractRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApi
     */
    public extract(requestParameters: APIServicesApiExtractRequest, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).extract(requestParameters.extractInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Scrape Endpoint
     * @param {APIServicesApiScrapeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIServicesApi
     */
    public scrape(requestParameters: APIServicesApiScrapeRequest, options?: RawAxiosRequestConfig) {
        return APIServicesApiFp(this.configuration).scrape(requestParameters.scrapeInput, options).then((request) => request(this.axios, this.basePath));
    }
}

