# coding: utf-8

"""
    Scrapix API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from scrapix.models.structured_output_format import StructuredOutputFormat
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StructuredOutput(BaseModel):
    """
    Structured output model for the response. This model is used to represent structured data extracted from the response.
    """ # noqa: E501
    data: StrictStr = Field(description="Structured data extracted from the response")
    data_schema: Optional[Dict[str, Any]] = None
    format: Optional[StructuredOutputFormat] = Field(default=None, description="Format of the structured output")
    cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=0.0, description="Cost incurred for generating the structured output")
    __properties: ClassVar[List[str]] = ["data", "data_schema", "format", "cost"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StructuredOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if data_schema (nullable) is None
        # and model_fields_set contains the field
        if self.data_schema is None and "data_schema" in self.model_fields_set:
            _dict['data_schema'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StructuredOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data": obj.get("data"),
            "data_schema": obj.get("data_schema"),
            "format": obj.get("format"),
            "cost": obj.get("cost") if obj.get("cost") is not None else 0.0
        })
        return _obj


