/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StructuredOutputFormat } from './structured-output-format';

/**
 * Input schema for collecting URLs from a page. `/collect`
 * @export
 * @interface CollectInput
 */
export interface CollectInput {
    [key: string]: any;

    /**
     * Unique identifier for the scraping task
     * @type {string}
     * @memberof CollectInput
     */
    'id'?: string;
    /**
     * Input URL
     * @type {string}
     * @memberof CollectInput
     */
    'url': string;
    /**
     * Timeout in seconds for the request
     * @type {number}
     * @memberof CollectInput
     */
    'timeout'?: number;
    /**
     * Max retries before failing
     * @type {number}
     * @memberof CollectInput
     */
    'max_retries'?: number;
    /**
     * 
     * @type {number}
     * @memberof CollectInput
     */
    'max_cost'?: number | null;
    /**
     * Render the Page
     * @type {boolean}
     * @memberof CollectInput
     */
    'render'?: boolean;
    /**
     * Use premium proxy
     * @type {boolean}
     * @memberof CollectInput
     */
    'premium_proxies'?: boolean;
    /**
     * Use captcha solvers to avoid blocking
     * @type {boolean}
     * @memberof CollectInput
     */
    'use_captcha_solver'?: boolean;
    /**
     * If enabled will serve from fresh crawl
     * @type {boolean}
     * @memberof CollectInput
     */
    'use_cache'?: boolean;
    /**
     * Maximum number of URLs to collect
     * @type {number}
     * @memberof CollectInput
     */
    'urls_limit'?: number;
    /**
     * 
     * @type {string}
     * @memberof CollectInput
     */
    'exclude_paths'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectInput
     */
    'include_paths'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectInput
     */
    'query'?: string | null;
    /**
     * Include URLs from SiteMap
     * @type {boolean}
     * @memberof CollectInput
     */
    'include_sitemap_urls'?: boolean;
    /**
     * The format of the output
     * @type {StructuredOutputFormat}
     * @memberof CollectInput
     */
    'output_format'?: StructuredOutputFormat;
}



