/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OutputFormat } from './output-format';
// May contain unused imports in some cases
// @ts-ignore
import type { StructuredOutputSchema } from './structured-output-schema';
// May contain unused imports in some cases
// @ts-ignore
import type { SummarizeSchema } from './summarize-schema';

/**
 * 
 * @export
 * @interface ScrapeInput
 */
export interface ScrapeInput {
    [key: string]: any;

    /**
     * Unique identifier for the scraping task
     * @type {string}
     * @memberof ScrapeInput
     */
    'id'?: string;
    /**
     * Input URL
     * @type {string}
     * @memberof ScrapeInput
     */
    'url': string;
    /**
     * Timeout in seconds for the request
     * @type {number}
     * @memberof ScrapeInput
     */
    'timeout'?: number;
    /**
     * Max retries before failing
     * @type {number}
     * @memberof ScrapeInput
     */
    'max_retries'?: number;
    /**
     * 
     * @type {number}
     * @memberof ScrapeInput
     */
    'max_cost'?: number | null;
    /**
     * Render the Page
     * @type {boolean}
     * @memberof ScrapeInput
     */
    'render'?: boolean;
    /**
     * Use premium proxy
     * @type {boolean}
     * @memberof ScrapeInput
     */
    'premium_proxies'?: boolean;
    /**
     * Use captcha solvers to avoid blocking
     * @type {boolean}
     * @memberof ScrapeInput
     */
    'use_captcha_solver'?: boolean;
    /**
     * If enabled will serve from fresh crawl
     * @type {boolean}
     * @memberof ScrapeInput
     */
    'use_cache'?: boolean;
    /**
     * The format of the output
     * @type {OutputFormat}
     * @memberof ScrapeInput
     */
    'output_format'?: OutputFormat;
    /**
     * 
     * @type {StructuredOutputSchema}
     * @memberof ScrapeInput
     */
    'structured_schema'?: StructuredOutputSchema | null;
    /**
     * 
     * @type {SummarizeSchema}
     * @memberof ScrapeInput
     */
    'summarize_schema'?: SummarizeSchema | null;
}



