/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Data1 } from './data1';
// May contain unused imports in some cases
// @ts-ignore
import type { StructuredOutputFormat } from './structured-output-format';

/**
 * Structured output model for the response. This model is used to represent structured data extracted from the response.
 * @export
 * @interface StructuredOutput
 */
export interface StructuredOutput {
    [key: string]: any;

    /**
     * 
     * @type {Data1}
     * @memberof StructuredOutput
     */
    'data': Data1;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StructuredOutput
     */
    'data_schema'?: { [key: string]: any; } | null;
    /**
     * Format of the structured output
     * @type {StructuredOutputFormat}
     * @memberof StructuredOutput
     */
    'format'?: StructuredOutputFormat;
    /**
     * Cost incurred for generating the structured output
     * @type {number}
     * @memberof StructuredOutput
     */
    'cost'?: number;
}



