/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StructuredOutputFormat } from './structured-output-format';

/**
 * 
 * @export
 * @interface StructuredOutputSchema
 */
export interface StructuredOutputSchema {
    /**
     * The format of the structured output schema
     * @type {StructuredOutputFormat}
     * @memberof StructuredOutputSchema
     */
    'format'?: StructuredOutputFormat;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof StructuredOutputSchema
     */
    'schema'?: { [key: string]: any; } | null;
    /**
     * A user query on what to extract from the structured output
     * @type {string}
     * @memberof StructuredOutputSchema
     */
    'query': string;
}



